Code refactoring
dumitrumunteanu/laravelProject pull request #7
Opened 2022-01-19 01:18 UTC by dumitrumunteanu

2022-01-19 05:14 UTC, egorbwork requested changes
The ModelLogger part looks correct. But creation of RequestLogger is invalid for the moment. Content looks reversed and does not look as one is extension of another one.

2022-01-19 05:14 UTC, egorbwork commented on app/Models/Post.php
> +class Post extends Model implements LoggableInterface
It is name of your Article model?

2022-01-19 05:14 UTC, egorbwork commented on app/Services/DebugRequestActivityLog.php
> +            'ip' => $request->ip(),
mistake

2022-01-19 05:14 UTC, egorbwork commented on app/Services/ProductionRequestActivityLog.php
> +        return $request->all();
mistake

2022-01-19 13:47 UTC, dumitrumunteanu commented on app/Models/Post.php
> +class Post extends Model implements LoggableInterface
Yes, it is.

2022-01-20 17:56 UTC, egorbwork approved these changes
Now looks fine.

2022-01-20 21:29 UTC, closed without merging